common: &common
  adapter: postgresql
  username: myapp
  password: password # from psql setup, see Postgresql

development:
  <<: *common
  database: myapp_development

test:
  <<: *common
  database: myapp_test

production:
  <<: *common
  host: ec2-23-23-183-144.compute-1.amazonaws.com/
  database: bojxzslyxv
  user: bojxzslyxv
  password: DtY8BScWU47vZ6cm6HTx
